import 'dart:async';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:uuid/uuid.dart';

import '../../../data/models/area_prediction.dart';

/// Widget-local search controller for the map picker's typed search. Owns the
/// debounce, latest-query generation guard, per-query cancel token, and the
/// autocomplete session token. NOT a Riverpod provider (would leak state across
/// picker instances).
class AreaSearchController extends ChangeNotifier {
  AreaSearchController({
    required this.search,
    required this.deepSearch,
    this.debounce = const Duration(milliseconds: 300),
    this.minChars = 2,
    String Function()? newToken,
  }) : _newToken = newToken ?? (() => const Uuid().v4());

  /// Injected so tests can drive it without a real Dio.
  final Future<List<AreaPrediction>> Function(
    String q,
    String sessionToken,
    CancelToken cancel,
  )
  search;
  final Future<DeepAreaSearchResponse> Function(String q, CancelToken cancel)
  deepSearch;
  final Duration debounce;
  final int minChars;
  final String Function() _newToken;

  Timer? _timer;
  CancelToken? _cancel;
  int _gen = 0;
  String _lastQuery = '';
  String? _inFlightDeepQuery;

  /// The query the deep `POST /geo/search` tier has already answered. Kept
  /// separate from [_inFlightDeepQuery] (which clears on completion) because
  /// this must OUTLIVE the call — it is what tells the dropdown there is no
  /// second tier left to offer for the current query.
  String? _deepSearchedQuery;
  String? _sessionToken;

  bool loading = false;
  String? error;
  List<AreaPrediction> results = const [];

  /// Lazily minted; reused for a search + its resolve; regenerated by [afterResolve]/[reset].
  String get sessionToken => _sessionToken ??= _newToken();

  /// True when the deeper `POST /geo/search` tier is still available for the
  /// current query — i.e. [submitQuery] has not yet succeeded for it.
  ///
  /// PROD — the pickers reach that tier only through the keyboard's Search
  /// key, which users don't discover, so the dropdown renders a "Load more
  /// results" row off this flag. Deliberately ignores [results]: the empty
  /// case is the one that needs the row MOST (a city absent from our DB is
  /// exactly what the deep tier exists to find). A FAILED deep call leaves
  /// this true so the row can be tried again; [error] is what the dropdown
  /// renders in the meantime.
  bool get canLoadMore =>
      !loading &&
      _lastQuery.length >= minChars &&
      _deepSearchedQuery != _lastQuery;

  void onQueryChanged(String raw) {
    final q = raw.trim();
    if (q == _lastQuery) return;
    _lastQuery = q;

    _timer?.cancel();
    _cancel?.cancel('new query');
    _cancel = CancelToken();
    _inFlightDeepQuery = null;
    _deepSearchedQuery = null; // a new query has an unspent deep tier again
    _gen++;

    if (q.length < minChars) {
      results = const [];
      loading = false;
      error = null;
      notifyListeners();
      return;
    }

    loading = true;
    error = null;
    notifyListeners();
    final gen = _gen;
    final cancel = _cancel!;
    _timer = Timer(debounce, () => _run(q, gen, cancel));
  }

  Future<void> _run(String q, int gen, CancelToken cancel) async {
    try {
      final r = await search(q, sessionToken, cancel);
      if (gen != _gen) return; // superseded
      results = r;
      loading = false;
      error = null;
      notifyListeners();
    } catch (e) {
      if (gen != _gen) return;
      if (e is DioException && CancelToken.isCancel(e)) {
        return; // ignore cancels
      }
      loading = false;
      error = e.toString();
      notifyListeners();
    }
  }

  /// Submit the field for local geography + venue search and optional backend
  /// fallback. This shares the autocomplete generation/cancellation lane:
  ///
  /// autocomplete ──submit──> cancel + deep search
  /// deep search ──edit──────> cancel + debounced autocomplete
  ///
  /// Only the latest generation may publish results.
  Future<void> submitQuery(String raw) async {
    final q = raw.trim();
    if (q.length < minChars) return;
    if (_inFlightDeepQuery == q) return;

    _timer?.cancel();
    _cancel?.cancel('submitted');
    final cancel = CancelToken();
    _cancel = cancel;
    final gen = ++_gen;
    _lastQuery = q;
    _inFlightDeepQuery = q;
    loading = true;
    error = null;
    notifyListeners();

    try {
      final response = await deepSearch(q, cancel);
      if (gen != _gen) return;
      // Success (even with zero results) spends the deep tier for this query:
      // the dropdown drops the "Load more results" row and falls back to its
      // no-matches message, which is now the truthful answer.
      _deepSearchedQuery = q;
      results = response.results;
      loading = false;
      error = response.partial && response.results.isEmpty
          ? 'deep search providers unavailable'
          : null;
      notifyListeners();
    } catch (e) {
      if (gen != _gen) return;
      if (e is DioException && CancelToken.isCancel(e)) {
        return;
      }
      loading = false;
      error = e.toString();
      notifyListeners();
    } finally {
      if (gen == _gen) {
        _inFlightDeepQuery = null;
      }
    }
  }

  /// A Places autocomplete session ends on resolve/details — start a fresh one.
  void afterResolve() => _sessionToken = null;

  /// Full reset (field clear): stop work, drop results, new session next time.
  void reset() {
    _timer?.cancel();
    _cancel?.cancel('reset');
    _gen++;
    _lastQuery = '';
    _inFlightDeepQuery = null;
    _deepSearchedQuery = null;
    _sessionToken = null;
    results = const [];
    loading = false;
    error = null;
    notifyListeners();
  }

  @override
  void dispose() {
    _timer?.cancel();
    _cancel?.cancel('disposed');
    super.dispose();
  }
}
